package dev.share.bytecodelens.decompile;

import dev.share.bytecodelens.util.AccessFlags;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.util.Textifier;
import org.objectweb.asm.util.TraceClassVisitor;

import java.io.PrintWriter;
import java.io.StringWriter;

/**
 * Last-resort decompiler. It never throws and always produces <em>something</em> readable —
 * a skeleton view of the class generated purely from ASM metadata, plus the raw Textifier
 * bytecode listing at the bottom. Use it when CFR / Vineflower / Procyon all fail.
 *
 * <p>The output is not valid Java. Each method body is a single comment with the
 * instruction count, and field initialisers aren't recovered. But every class — even
 * ones that crash the three real decompilers — produces readable structural output.</p>
 */
public final class FallbackDecompiler implements ClassDecompiler {

    @Override public String name() { return "Fallback"; }

    @Override
    public String decompile(String internalName, byte[] classBytes) {
        try {
            return render(classBytes);
        } catch (Throwable ex) {
            // Even the metadata reader shouldn't fail, but if it does we at least report that.
            return "// Fallback decompiler: failed to read class bytes — "
                    + ex.getClass().getSimpleName() + ": " + ex.getMessage();
        }
    }

    private String render(byte[] classBytes) {
        ClassNode node = new ClassNode();
        new ClassReader(classBytes).accept(node, ClassReader.SKIP_FRAMES);

        StringBuilder sb = new StringBuilder(8192);
        sb.append("// Generated by BytecodeLens fallback decompiler.\n");
        sb.append("// This is a structural skeleton, not compilable Java. See the bytecode\n");
        sb.append("// section at the bottom if you need opcode-level detail.\n\n");

        // Package.
        int lastSlash = node.name.lastIndexOf('/');
        if (lastSlash > 0) {
            sb.append("package ").append(node.name.substring(0, lastSlash).replace('/', '.')).append(";\n\n");
        }

        // Class declaration.
        appendAccessFlags(sb, AccessFlags.forClass(node.access));
        if ((node.access & Opcodes.ACC_INTERFACE) != 0) {
            // "interface" already included in forClass().
        } else if ((node.access & Opcodes.ACC_ENUM) != 0) {
            // "enum" already included.
        } else if ((node.access & Opcodes.ACC_ANNOTATION) != 0) {
            // "annotation" already included.
        } else if ((node.access & Opcodes.ACC_RECORD) != 0) {
            // "record" already included.
        } else {
            sb.append("class ");
        }
        sb.append(simpleName(node.name));
        if (node.superName != null && !node.superName.equals("java/lang/Object")) {
            sb.append(" extends ").append(node.superName.replace('/', '.'));
        }
        if (node.interfaces != null && !node.interfaces.isEmpty()) {
            sb.append(" implements ");
            for (int i = 0; i < node.interfaces.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(node.interfaces.get(i).replace('/', '.'));
            }
        }
        sb.append(" {\n\n");

        // Fields.
        if (node.fields != null) {
            for (FieldNode f : node.fields) {
                sb.append("    ");
                appendAccessFlags(sb, AccessFlags.forField(f.access));
                sb.append(humanType(Type.getType(f.desc))).append(' ').append(f.name);
                if (f.value != null) {
                    sb.append(" = ").append(literalFor(f.value));
                }
                sb.append(";\n");
            }
            if (!node.fields.isEmpty()) sb.append('\n');
        }

        // Methods.
        if (node.methods != null) {
            for (MethodNode m : node.methods) {
                sb.append("    ");
                appendAccessFlags(sb, AccessFlags.forMethod(m.access));
                Type mt = Type.getMethodType(m.desc);
                sb.append(humanType(mt.getReturnType())).append(' ');
                sb.append(m.name).append('(');
                Type[] args = mt.getArgumentTypes();
                for (int i = 0; i < args.length; i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(humanType(args[i])).append(" arg").append(i);
                }
                sb.append(')');
                if (m.exceptions != null && !m.exceptions.isEmpty()) {
                    sb.append(" throws ");
                    for (int i = 0; i < m.exceptions.size(); i++) {
                        if (i > 0) sb.append(", ");
                        sb.append(m.exceptions.get(i).replace('/', '.'));
                    }
                }
                if ((m.access & (Opcodes.ACC_ABSTRACT | Opcodes.ACC_NATIVE)) != 0) {
                    sb.append(";\n");
                } else {
                    int insnCount = m.instructions == null ? 0 : m.instructions.size();
                    sb.append(" { /* ").append(insnCount).append(" instruction(s) — see bytecode listing */ }\n");
                }
            }
        }
        sb.append("}\n\n");

        // Raw bytecode appendix.
        sb.append("/* ============================================================\n");
        sb.append(" * BYTECODE LISTING (ASM Textifier)\n");
        sb.append(" * ============================================================\n");
        sb.append(" */\n");
        try {
            StringWriter sw = new StringWriter();
            try (PrintWriter pw = new PrintWriter(sw)) {
                new ClassReader(classBytes).accept(
                        new TraceClassVisitor(null, new Textifier(), pw),
                        ClassReader.SKIP_FRAMES);
            }
            String listing = sw.toString();
            // Keep size bounded so huge classes don't blow the viewer up.
            int limit = 40_000;
            if (listing.length() > limit) {
                listing = listing.substring(0, limit) + "\n// ... truncated ...\n";
            }
            sb.append(listing);
        } catch (Throwable ex) {
            sb.append("// Textifier failed: ").append(ex).append('\n');
        }
        return sb.toString();
    }

    private static void appendAccessFlags(StringBuilder sb, java.util.List<String> flags) {
        for (String f : flags) sb.append(f).append(' ');
    }

    private static String simpleName(String internal) {
        int slash = internal.lastIndexOf('/');
        return slash < 0 ? internal : internal.substring(slash + 1);
    }

    private static String humanType(Type t) {
        return switch (t.getSort()) {
            case Type.VOID -> "void";
            case Type.BOOLEAN -> "boolean";
            case Type.BYTE -> "byte";
            case Type.CHAR -> "char";
            case Type.SHORT -> "short";
            case Type.INT -> "int";
            case Type.LONG -> "long";
            case Type.FLOAT -> "float";
            case Type.DOUBLE -> "double";
            case Type.ARRAY -> humanType(t.getElementType()) + "[]".repeat(t.getDimensions());
            case Type.OBJECT -> t.getClassName();
            default -> "?";
        };
    }

    private static String literalFor(Object value) {
        if (value instanceof String s) return "\"" + s.replace("\"", "\\\"") + "\"";
        if (value instanceof Long l) return l + "L";
        if (value instanceof Float f) return f + "f";
        if (value instanceof Double d) return d + "d";
        return String.valueOf(value);
    }
}
