package dev.share.bytecodelens.service;

import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

import java.util.ArrayList;
import java.util.List;

/**
 * Generates ready-to-paste hook snippets for Frida and Xposed — the two most common
 * runtime instrumentation frameworks used in Android / JVM reverse engineering.
 *
 * <p>Output uses the exact method descriptor for overload disambiguation, so a snippet
 * targets one specific method signature (not all methods with the same name).</p>
 */
public final class HookSnippetGenerator {

    /**
     * @param classInternalName e.g. {@code "com/foo/Bar"} — slash form
     * @param methodName        method name; {@code <init>} for constructors
     * @param descriptor        JVMS method descriptor, e.g. {@code (ILjava/lang/String;)V}
     * @param access            method access flags (ACC_STATIC check for {@code static})
     * @return JavaScript snippet ready to paste into a Frida script
     */
    public String frida(String classInternalName, String methodName, String descriptor, int access) {
        String dotted = classInternalName.replace('/', '.');
        boolean isStatic = (access & Opcodes.ACC_STATIC) != 0;
        boolean isCtor = "<init>".equals(methodName);
        Type method = Type.getMethodType(descriptor);
        Type[] argTypes = method.getArgumentTypes();
        Type returnType = method.getReturnType();

        String jsClassVar = safeIdent(lastSegment(dotted));
        String fridaMethodName = isCtor ? "$init" : methodName;
        String overloadArgs = joinOverload(argTypes);
        String implArgs = argNames(argTypes);
        String callArgs = implArgs;
        String logArgs = logArgList(argTypes);
        String returnsVoid = returnType.getSort() == Type.VOID ? "" : "return ";
        String resultCapture = returnType.getSort() == Type.VOID ? "" : "var result = ";
        String resultLog = returnType.getSort() == Type.VOID
                ? ""
                : "        console.log('[+] " + dotted + "." + methodName + " -> ' + result);\n";
        String returnStmt = returnType.getSort() == Type.VOID ? "" : "        return result;\n";
        String receiver = isStatic ? jsClassVar : "this";

        StringBuilder out = new StringBuilder();
        out.append("// Frida hook — ").append(dotted).append('.').append(methodName)
                .append(descriptor).append('\n');
        out.append("// Generated by BytecodeLens\n");
        out.append("Java.perform(function () {\n");
        out.append("    var ").append(jsClassVar).append(" = Java.use('").append(dotted).append("');\n");
        out.append("    ").append(jsClassVar).append('.').append(fridaMethodName)
                .append(".overload(").append(overloadArgs).append(").implementation = function (")
                .append(implArgs).append(") {\n");
        out.append("        console.log('[+] ").append(dotted).append('.').append(methodName).append("(' ")
                .append(logArgs).append(" ')');\n");
        out.append("        ").append(resultCapture).append(receiver).append('.')
                .append(fridaMethodName).append('(').append(callArgs).append(");\n");
        out.append(resultLog);
        out.append(returnStmt);
        out.append("    };\n");
        out.append("});\n");
        return out.toString();
    }

    /**
     * Xposed {@code findAndHookMethod} snippet. Unlike Frida, Xposed identifies a method by
     * parameter class references rather than a descriptor string, so we emit {@code Type.class}
     * literals.
     */
    public String xposed(String classInternalName, String methodName, String descriptor, int access) {
        String dotted = classInternalName.replace('/', '.');
        boolean isCtor = "<init>".equals(methodName);
        Type method = Type.getMethodType(descriptor);
        Type[] argTypes = method.getArgumentTypes();

        StringBuilder out = new StringBuilder();
        out.append("// Xposed hook — ").append(dotted).append('.').append(methodName)
                .append(descriptor).append('\n');
        out.append("// Generated by BytecodeLens — paste into handleLoadPackage\n");
        if (isCtor) {
            out.append("XposedHelpers.findAndHookConstructor(\n");
            out.append("        \"").append(dotted).append("\",\n");
            out.append("        lpparam.classLoader,\n");
        } else {
            out.append("XposedHelpers.findAndHookMethod(\n");
            out.append("        \"").append(dotted).append("\",\n");
            out.append("        lpparam.classLoader,\n");
            out.append("        \"").append(methodName).append("\",\n");
        }
        for (Type t : argTypes) {
            out.append("        ").append(xposedParamLiteral(t)).append(",\n");
        }
        out.append("        new XC_MethodHook() {\n");
        out.append("            @Override\n");
        out.append("            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {\n");
        out.append("                XposedBridge.log(\"[+] ").append(dotted).append('.').append(methodName)
                .append(" called\");\n");
        out.append("            }\n");
        out.append("            @Override\n");
        out.append("            protected void afterHookedMethod(MethodHookParam param) throws Throwable {\n");
        out.append("                XposedBridge.log(\"[+] ").append(dotted).append('.').append(methodName)
                .append(" returned: \" + param.getResult());\n");
        out.append("            }\n");
        out.append("        });\n");
        return out.toString();
    }

    // --- helpers ---------------------------------------------------------------

    /** Frida expects JNI-style strings in overload(): primitives as 'int', refs as dotted 'java.lang.String'. */
    private static String joinOverload(Type[] args) {
        List<String> quoted = new ArrayList<>();
        for (Type t : args) {
            quoted.add("'" + fridaTypeName(t) + "'");
        }
        return String.join(", ", quoted);
    }

    private static String fridaTypeName(Type t) {
        return switch (t.getSort()) {
            case Type.BOOLEAN -> "boolean";
            case Type.BYTE -> "byte";
            case Type.CHAR -> "char";
            case Type.SHORT -> "short";
            case Type.INT -> "int";
            case Type.LONG -> "long";
            case Type.FLOAT -> "float";
            case Type.DOUBLE -> "double";
            case Type.VOID -> "void";
            case Type.ARRAY -> t.getDescriptor().replace('/', '.'); // '[Ljava.lang.String;' etc
            case Type.OBJECT -> t.getClassName(); // already dotted
            default -> "?";
        };
    }

    /** Generates `arg0, arg1, ...` for function signatures. */
    private static String argNames(Type[] args) {
        List<String> names = new ArrayList<>();
        for (int i = 0; i < args.length; i++) names.add("arg" + i);
        return String.join(", ", names);
    }

    /** Generates `+ arg0 + ', ' + arg1` for a console.log of arg values. */
    private static String logArgList(Type[] args) {
        if (args.length == 0) return "+ ''";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < args.length; i++) {
            if (i == 0) sb.append("+ arg0");
            else sb.append(" + ', ' + arg").append(i);
        }
        return sb.toString();
    }

    /** Xposed wants {@code int.class}, {@code String.class}, {@code int[].class} etc. */
    private static String xposedParamLiteral(Type t) {
        return switch (t.getSort()) {
            case Type.BOOLEAN -> "boolean.class";
            case Type.BYTE -> "byte.class";
            case Type.CHAR -> "char.class";
            case Type.SHORT -> "short.class";
            case Type.INT -> "int.class";
            case Type.LONG -> "long.class";
            case Type.FLOAT -> "float.class";
            case Type.DOUBLE -> "double.class";
            case Type.ARRAY -> {
                // int[] / String[][] — use Java syntax
                String element = xposedParamLiteralForElement(t.getElementType());
                int dims = t.getDimensions();
                yield element.replace(".class", "[]".repeat(dims) + ".class");
            }
            case Type.OBJECT -> "\"" + t.getClassName() + "\""; // class name as string works for findAndHookMethod
            default -> "Object.class";
        };
    }

    private static String xposedParamLiteralForElement(Type t) {
        return switch (t.getSort()) {
            case Type.BOOLEAN -> "boolean.class";
            case Type.BYTE -> "byte.class";
            case Type.CHAR -> "char.class";
            case Type.SHORT -> "short.class";
            case Type.INT -> "int.class";
            case Type.LONG -> "long.class";
            case Type.FLOAT -> "float.class";
            case Type.DOUBLE -> "double.class";
            case Type.OBJECT -> lastSegment(t.getClassName()) + ".class";
            default -> "Object.class";
        };
    }

    private static String lastSegment(String dotted) {
        int dot = dotted.lastIndexOf('.');
        return dot < 0 ? dotted : dotted.substring(dot + 1);
    }

    /** Strip generic arguments / brackets from a class simple name so it's a valid JS identifier. */
    private static String safeIdent(String s) {
        StringBuilder sb = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (Character.isJavaIdentifierPart(c)) sb.append(c);
        }
        if (sb.length() == 0 || !Character.isJavaIdentifierStart(sb.charAt(0))) {
            sb.insert(0, '_');
        }
        return sb.toString();
    }
}
